"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const FAQ_ITEMS = [
  {
    q: "Is the AI content detectable?",
    a: "Our 3-stage pipeline (research → outline → write) produces structured, factual content that reads naturally. We recommend reviewing articles before publishing and adding your own examples or insights.",
  },
  {
    q: "Will Google penalize AI-generated content?",
    a: "Google's guidelines focus on quality and helpfulness, not authorship. Articles generated by Geek SEO Autopilot are fact-researched, properly structured, and optimized for both readers and search engines.",
  },
  {
    q: "What CMS platforms are supported?",
    a: "WordPress is fully supported with application password authentication. Webflow, Shopify, Wix, and custom REST APIs are on the roadmap. You can always copy-paste content from the editor.",
  },
  {
    q: "How many articles can I generate per month?",
    a: "Starter plan includes 20 articles/month, Pro includes 100, and Business is unlimited. Each article generation calls Claude AI three times (research, outline, write), so limits are based on API usage.",
  },
  {
    q: "Can I edit articles after they're generated?",
    a: "Yes — every article opens in a full markdown editor with live SEO scoring. Edit freely, and the score updates in real-time as you type.",
  },
  {
    q: "Is there a free trial?",
    a: "Sign in with Google to get started — the dashboard is free. All paid plans include a 14-day free trial with no credit card required.",
  },
  {
    q: "What AI model does it use?",
    a: "We use Anthropic's Claude claude-opus-4-6 with the web_search tool enabled, so articles are grounded in real, current search results — not just training data.",
  },
];

export function FAQSection() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <section id="faq" className="py-20 bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
            Frequently asked questions
          </h2>
        </div>

        <div className="space-y-3">
          {FAQ_ITEMS.map((item, i) => (
            <div
              key={i}
              className="border border-slate-200 rounded-xl overflow-hidden"
            >
              <button
                className="w-full flex items-center justify-between px-6 py-4 text-left hover:bg-slate-50 transition-colors"
                onClick={() => setOpen(open === i ? null : i)}
              >
                <span className="font-semibold text-slate-900 pr-4">
                  {item.q}
                </span>
                <ChevronDown
                  className={cn(
                    "w-5 h-5 text-slate-400 shrink-0 transition-transform",
                    open === i && "rotate-180"
                  )}
                />
              </button>
              {open === i && (
                <div className="px-6 pb-5 text-slate-600 leading-relaxed">
                  {item.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
